---
- hosts: localhost
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: wizcli -h
      register: wiz_test_output
    - name: assert binary prints help output
      debug:
        msg: '{{ wiz_test_output.stdout + wiz_test_output.stderr }}'
