---
- name: check for {{ wiz_installed_exe }}
  become: yes
  stat:
    path: '{{ wiz_installed_exe }}'
  changed_when: False
  register: wiz_binary
- when: not wiz_binary.stat.exists
  block:
    - name: mkdir {{ wiz_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ wiz_install_dir }}'
        state: directory
        mode: 0755
    - name: download {{ wiz_url }}...
      become: yes
      become_user: root
      get_url:
        url: '{{ wiz_url }}'
        dest: '{{ wiz_installed_exe }}'
        mode: 0755
- name: link {{ wiz_installed_link }} to {{ wiz_installed_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ wiz_installed_exe }}'
    dest: '{{ wiz_installed_link }}'
    state: link
